const iso = (d) => d && d.year ? `${d.year}-${String(d.month||1).padStart(2,'0')}-${String(d.day||1).padStart(2,'0')}` : '';
const pname = (n) => !n ? '' : (typeof n === 'string' ? n : [n.firstName, n.middleName, n.lastName].filter(Boolean).join(' '));
const primaryUrl = (arr) => Array.isArray(arr) ? (arr.find(w => w.isPrimary === 'Yes')?.url || arr[0]?.url || '') : '';
const uniq = (a) => [...new Set(a.filter(Boolean))];
function taxonomy(paths){const pa=[],feeds=[];for(const path of (paths||[]))for(const node of path){if(node.type==='PRACTICE AREA'&&node.classification==='Other Markets')pa.push(node.name);if(node.type==='FEED')feeds.push(node.name);}return{sectors:uniq(pa),feeds:uniq(feeds)};}
export function flattenCompany(c){
  const tx=taxonomy(c.primaryTaxonomy);const hq=(c.locations&&c.locations[0])||{};
  const reg=(c.contact?.addresses||[]).find(a=>a.isRegisteredAddress==='Yes')||{};
  const inv=c.investors||[];const invNames=inv.map(i=>pname(i.name));
  const leads=inv.filter(i=>i.isLeadInAnyFundingRound==='Yes').map(i=>pname(i.name));
  const le=(c.legalEntities||[])[0]||{};const rev=c.latestRevenue||{};
  return{tracxn_id:c.id||'',name:c.name||'',website:primaryUrl(c.website),founded_year:c.foundedYear||'',stage:c.stage||'',funded:c.funded||'',xcorn:c.xcorn?.rating||'',short_description:c.shortDescription||'',detailed_description:c.detailedDescription||'',hq_city:hq.city?.name||'',hq_state:hq.state?.name||'',hq_country:hq.country?.name||(c.contact?.addresses?.[0]?.location?.country?.name||''),registered_address:(reg.addressText||'').replace(/\s+/g,' ').trim(),pincode:reg.pincode||'',emails:(c.contact?.emails||[]).join('; '),founders:(c.founders||[]).map(f=>pname(f.name)).filter(Boolean).join('; '),founder_dins:(c.founders||[]).flatMap(f=>(f.directorIdNumbers||[]).map(d=>d.id)).filter(Boolean).join('; '),key_people:(c.keyPeople||[]).map(p=>`${pname(p.name)}${p.designation?' ('+p.designation+')':''}`).filter(Boolean).join('; '),has_female_founder:c.hasFemaleFounder||'',latest_funding_round:c.latestFundingRound?.name||'',latest_funding_date:iso(c.latestFundingRound?.date),total_equity_funding_usd:c.totalEquityFunding?.amount?.USD?.value??'',total_equity_funding_inr:c.totalEquityFunding?.amount?.INR?.value??'',investor_count:inv.length,investors:invNames.filter(Boolean).join('; '),lead_investors:leads.filter(Boolean).join('; '),latest_revenue_inr:rev.amount?.INR?.value??'',latest_revenue_usd:rev.amount?.USD?.value??'',revenue_as_on:iso(rev.asOnDate),revenue_growth_1y_pct:rev.growthDetails?.oneYear?.CAGR??'',net_profit_as_on:iso(c.latestNetProfit?.asOnDate),ebitda_as_on:iso(c.latestEBITDA?.asOnDate),sectors:tx.sectors.join('; '),feeds:tx.feeds.join('; '),legal_entity_name:le.name||'',cin:le.entityId||'',registrar:le.registrar||'',entity_type:le.mappedEntityType||'',incubators:(c.incubators||[]).map(i=>i.company?.name).filter(Boolean).join('; '),linkedin:c.socialMediaProfiles?.linkedin||'',tracxn_score:c.tracxnScore?.overall!=null?Number(c.tracxnScore.overall).toFixed(1):'',editor_rating:c.editorRating?.rating??'',status:c.status||'',last_updated:iso(c.lastUpdatedDate),tracxn_url:c.tracxnPlatformUrl||''};
}
